using UnityEngine;
using UnityEngine.InputSystem;
using TMPro;

public class CursorChange : MonoBehaviour
{
    public PlayerInput pi;

    [SerializeField] private SpriteRenderer[] cursors;
    [SerializeField] private Transform joyCap;
    public Vector2 joyCapMoveTo;

    public Color color;
    private SpriteRenderer _spriteRenderer;
    
    [SerializeField] private TMP_Text sunText;
    
    //Initialise and assign variables

    private void Start()
    {
        _spriteRenderer = joyCap.gameObject.GetComponent<SpriteRenderer>();
        //Get the SpriteRenderer component from the joyCap object
        foreach (var t in cursors)
        {
            t.color = color;
            //Set the color of every cursor to the color variable. Color is generated by the Player.cs script
        }
        
        _spriteRenderer.color = color + new Color(0.1f, 0.1f, 0.1f);
        
        sunText.color = color;
    }
    
    private void Update()
    {
        switch (pi.currentControlScheme)
        {
            //Depending on the device the player is using, enable the appropriate cursor
            case "Controller":
                cursors[0].enabled = false;
                cursors[1].enabled = false;
                cursors[2].enabled = true;
                _spriteRenderer.enabled = true;
                //Enable the joystick cursor and disable the other two

                joyCap.localPosition = joyCapMoveTo / 3;
                //Move the joystick around the base of the joystick, to show what the player is doing with their physical joystick
                break;
            case "K&M":
                cursors[0].enabled = false;
                cursors[1].enabled = true;
                cursors[2].enabled = false;
                _spriteRenderer.enabled = false;
                //Enable the mouse cursor and disable the other two
                break;
            case "Touch":
                cursors[0].enabled = true;
                cursors[1].enabled = false;
                cursors[2].enabled = false;
                _spriteRenderer.enabled = false;
                //Enable the touch cursor and disable the other two
                break;
        }
    }
}
